name: flutter_module
description: A new Flutter module.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  dio: ^3.0.9
#  http: ^0.12.2
  transparent_image: ^1.0.0
  flutter_staggered_grid_view: ^0.3.1
  provider: 4.0.4 #状态管理 google推荐
  json_annotation: 3.0.1 #json解析
  flutter_screenutil: ^4.0.2+3 #屏幕适配f
  flutter_easyrefresh: ^2.1.1 #刷新组件
  pull_to_refresh: 1.5.8 #刷新组件
  url_launcher: ^5.1.3 #打电话

  event_bus: 1.1.1 #一个使用Dart流进行解耦应用程序的简单事件总线的库。
  # Flutter 城市列表，联系人列表，索引&悬停 https://github.com/flutterchina/azlistview
  azlistview: 0.1.2
  # Dart 汉字转拼音 https://github.com/flutterchina/lpinyin
  lpinyin: 1.0.7
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: 0.5.4 #侧滑删除等功能
  shared_preferences: ^0.5.12+4 # 用于读写简单键值对的Flutter插件。包装iOS上的NSUserDefaults和Android上的SharedPreferences。
#  connectivity: ^0.4.8+6 #网络状态监听
  flutter_swiper: 1.1.6 #轮播
  #  marquee_flutter: ^0.1.4 #跑马灯效果

  #  scroll_to_index: ^1.0.6

  #  image_gallery_saver: 1.2.2  #保存图片
  #  path_provider: 1.6.5 #获取路径
  permission_handler: ^3.0.1 #权限管理
#  fluttertoast: 4.0.0 #toast提示
  bot_toast: ^3.0.5

#  flutter_custom_dialog: ^1.0.4 #各种弹窗，掘金教程https://juejin.im/post/5d85b4a06fb9a06af238aef9

  intl: ^0.16.1 # 时间格式转换
#  cached_network_image: ^2.5.0 #Flutter库来加载和缓存网络图像。也可以与占位符和错误小部件一起使用。
  flutter_easyloading: ^1.1.3

  webview_flutter: ^0.3.22+1
  badges: ^1.1.1 #小红点
#  fluwx: ^2.1.0 #微信sdk
  dio_log: ^1.3.3
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  get: ^3.24.0
  device_info: ^0.4.2+4
  crypto: ^2.1.5
  qr_flutter: ^3.2.0
  flutter_qr_reader: ^1.0.3
  photo_view: 0.10.3
  dokit: ^0.2.12
#  thrio: ^1.7.11


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - static/images/
    - static/
  module:
    androidX: true
    androidPackage: com.chat.flutter.flutter_module
    iosBundleIdentifier: com.chat.flutter.flutterModule

